name: web
description: personal website
runtime:
    name: nodejs
    options:
        packagemanager: npm
config:
    pulumi:tags:
        value:
            pulumi:template: static-website-aws-typescript
